name: Automated Swift Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - 'version-*'

jobs:
  five:
    container: 
      image: swift:5.10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: swift build
    - run: swift test
